cargo-features = ["edition2021"]

[package]
name = "exercise"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-vec = "^0.6.3"
num = "^0.4.0"

[lib]
name = "algorithm"
path = "algorithm/lib.rs"
edition = "2021"

[workspace]
members = [
  "Codewars",
  "Project Euler",
]

