; 为下面的各个语言构建无二义性的上下文无关文法。证明你的文法是正确的。
;
; 1）用后缀方式表示的算数表达式。
; 2）由逗号分隔开的左结合的标识符列表。
; 3）由逗号分隔开的右结合的标识符列表。
; 4）由整数、标识符、四个耳目运算符 +、-、*、/ 构成的算数表达式。
; ！5）在 4）的运算符中增加单目 + 和单目 - 构成的算数表达式。

; 方便起见，定义一些通用的
<int> ::= [1-9] [0-9]*
<id> ::= ([a-z] | [A-Z] | "_") ([0-9] | [a-z] | [A-Z] | "_")*
<add> ::= "+" | "-"
<mul> ::= "*" | "/"
<op> ::= <add> | <mul>
<ws> ::= " " | "\t" | "\v" | "\f" | "\r" | "\n"

; 1）
<expr> ::= <expr> <ws> <expr> <ws> <op> | <int>

; 2）
<list> ::= <list> ", " <id> | <id>

; 3）
<list> ::= <id> ", " <list> | <id>

; 4）
<expr> ::= <expr> <ws> <add> <ws> <term> | <term>
<term> ::= <term> <ws> <mul> <ws> <fact> | <fact>
<fact> ::= <id> | <int>

; 5）
<expr> ::= <expr> <ws> <add> <ws> <term> | <term>
<term> ::= <term> <ws> <mul> <ws> <fact> | <fact>
<fact> ::= <add> <atom> | <atom>
<atom> ::= <id> | <int>
