; 方便起见，定义一些通用的
<int> ::= [1-9] [0-9]*
<id> ::= ([a-z] | [A-Z] | "_") ([0-9] | [a-z] | [A-Z] | "_")*
<add> ::= "+" | "-"
<mul> ::= "*" | "/"
<op> ::= <add> | <mul>
<ws> ::= " " | "\t" | "\v" | "\f" | "\r" | "\n"

; 1）
<expr> ::= <expr> <ws> <expr> <ws> <op> | <int>

; 2）
<list> ::= <list> ", " <id> | <id>

; 3）
<list> ::= <id> ", " <list> | <id>

; 4）
<expr> ::= <expr> <ws> <add> <ws> <term> | <term>
<term> ::= <term> <ws> <mul> <ws> <fact> | <fact>
<fact> ::= <id> | <int>

; 5）
<expr> ::= <expr> <ws> <add> <ws> <term> | <term>
<term> ::= <term> <ws> <mul> <ws> <fact> | <fact>
<fact> ::= <add> <atom> | <atom>
<atom> ::= <id> | <int>
